version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: fabrica-bebidas-app
      POSTGRES_PASSWORD: fabrica-bebidas-app-password
      POSTGRES_DB: fabrica-bebidas
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
